/**
 * Auto-generated execution implementation for dt_proxy ChiMod
 * Implements Container virtual APIs (Run, SaveTask, LoadTask, NewCopyTask, NewTask)
 * using switch-case dispatch
 * 
 * This file is autogenerated - do not edit manually.
 * Changes should be made to the autogen tool or the YAML configuration.
 */

#include "dt_provenance/dt_proxy/proxy_runtime.h"
#include "dt_provenance/dt_proxy/autogen/proxy_methods.h"
#include <clio_runtime/clio_runtime.h>
#include <clio_runtime/task.h>  // For TaskResume coroutine return type

namespace dt_provenance::proxy {

//==============================================================================
// Container Virtual API Implementations
//==============================================================================

void Runtime::Init(const clio::run::PoolId &pool_id, const std::string &pool_name,
                   clio::run::u32 container_id) {
  // Call base class initialization
  clio::run::Container::Init(pool_id, pool_name, container_id);

  // Initialize the client for this ChiMod
  client_ = Client(pool_id);

  // Initialize per-method load prediction model
  DefineModel(Method::kMaxMethodId);
  SetMethodNames(Method::GetMethodNames());
}

clio::run::TaskResume Runtime::Run(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task> task_ptr) {
  CLIO_TASK_BODY_BEGIN
  switch (method) {
    case Method::kCreate: {
      // Cast task handle to specific type (in-place reinterpret)
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      CLIO_CO_AWAIT(Create(typed_task));
      break;
    }
    case Method::kDestroy: {
      // Cast task handle to specific type (in-place reinterpret)
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      CLIO_CO_AWAIT(Destroy(typed_task));
      break;
    }
    case Method::kMonitor: {
      // Cast task handle to specific type (in-place reinterpret)
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      CLIO_CO_AWAIT(Monitor(typed_task));
      break;
    }
    case Method::kForwardHttp: {
      // Cast task handle to specific type (in-place reinterpret)
      auto& typed_task = task_ptr.template Cast<ForwardHttpTask>();
      CLIO_CO_AWAIT(ForwardHttp(typed_task));
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
  CLIO_CO_RETURN;
  CLIO_TASK_BODY_END
}

void Runtime::SaveTask(clio::run::u32 method, clio::run::SaveTaskArchive& archive, 
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive << *typed_task;
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = task_ptr.template Cast<ForwardHttpTask>();
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

void Runtime::LoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive,
                        clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      archive >> *typed_task;
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = task_ptr.template Cast<ForwardHttpTask>();
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::AllocLoadTask(clio::run::u32 method, clio::run::LoadTaskArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive,
                            clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = task_ptr.template Cast<ForwardHttpTask>();
      // Use archive operator which respects msg_type
      archive >> *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::LocalAllocLoadTask(clio::run::u32 method, clio::run::DefaultLoadArchive& archive) {
  clio::run::shared_ptr<clio::run::Task> task_ptr = NewTask(method);
  if (!task_ptr.IsNull()) {
    LocalLoadTask(method, archive, task_ptr);
  }
  return task_ptr;
}

void Runtime::LocalSaveTask(clio::run::u32 method, clio::run::DefaultSaveArchive& archive, 
                             clio::run::shared_ptr<clio::run::Task>& task_ptr) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = task_ptr.template Cast<CreateTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = task_ptr.template Cast<DestroyTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = task_ptr.template Cast<MonitorTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = task_ptr.template Cast<ForwardHttpTask>();
      // Use archive operator which respects msg_type
      archive << *typed_task;
      break;
    }
    default: {
      // Unknown method - do nothing
      break;
    }
  }
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewCopyTask(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task_ptr, bool deep) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<CreateTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<CreateTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kDestroy: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<DestroyTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<DestroyTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kMonitor: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<MonitorTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<MonitorTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    case Method::kForwardHttp: {
      // Allocate new task
      auto new_task_ptr = ipc_manager->NewTask<ForwardHttpTask>();
      if (!new_task_ptr.IsNull()) {
        // Copy task fields (includes base Task fields)
        auto& task_typed = orig_task_ptr.template Cast<ForwardHttpTask>();
        new_task_ptr->Copy(ctp::ipc::FullPtr<ForwardHttpTask>(task_typed.get()));
        return new_task_ptr.template Cast<clio::run::Task>();
      }
      break;
    }
    default: {
      // For unknown methods, create base Task copy
      auto new_task_ptr = ipc_manager->NewTask<clio::run::Task>();
      if (!new_task_ptr.IsNull()) {
        new_task_ptr->Copy(ctp::ipc::FullPtr<clio::run::Task>(orig_task_ptr.get()));
        return new_task_ptr;
      }
      break;
    }
  }
  
  (void)deep;    // Deep copy parameter reserved for future use
  return clio::run::shared_ptr<clio::run::Task>();
}

clio::run::shared_ptr<clio::run::Task> Runtime::NewTask(clio::run::u32 method) {
  auto* ipc_manager = CLIO_IPC;
  if (!ipc_manager) {
    return clio::run::shared_ptr<clio::run::Task>();
  }
  
  switch (method) {
    case Method::kCreate: {
      auto new_task_ptr = ipc_manager->NewTask<CreateTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kDestroy: {
      auto new_task_ptr = ipc_manager->NewTask<DestroyTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kMonitor: {
      auto new_task_ptr = ipc_manager->NewTask<MonitorTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    case Method::kForwardHttp: {
      auto new_task_ptr = ipc_manager->NewTask<ForwardHttpTask>();
      return new_task_ptr.template Cast<clio::run::Task>();
    }
    default: {
      // For unknown methods, return null pointer
      return clio::run::shared_ptr<clio::run::Task>();
    }
  }
}

void Runtime::AggregateOut(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& orig_task,
                        const clio::run::shared_ptr<clio::run::Task>& replica_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = orig_task.template Cast<CreateTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = orig_task.template Cast<DestroyTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = orig_task.template Cast<MonitorTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = orig_task.template Cast<ForwardHttpTask>();
      typed_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
    default: {
      orig_task->AggregateOut(ctp::ipc::FullPtr<clio::run::Task>(replica_task.get()));
      break;
    }
  }
}

void Runtime::AggregateIn(clio::run::u32 method, clio::run::shared_ptr<clio::run::Task>& agg_task,
                        const clio::run::shared_ptr<clio::run::Task>& member_task) {
  switch (method) {
    case Method::kCreate: {
      auto& typed_task = agg_task.template Cast<CreateTask>();
      typed_task->AggregateIn(ctp::ipc::FullPtr<clio::run::Task>(member_task.get()));
      break;
    }
    case Method::kDestroy: {
      auto& typed_task = agg_task.template Cast<DestroyTask>();
      typed_task->AggregateIn(ctp::ipc::FullPtr<clio::run::Task>(member_task.get()));
      break;
    }
    case Method::kMonitor: {
      auto& typed_task = agg_task.template Cast<MonitorTask>();
      typed_task->AggregateIn(ctp::ipc::FullPtr<clio::run::Task>(member_task.get()));
      break;
    }
    case Method::kForwardHttp: {
      auto& typed_task = agg_task.template Cast<ForwardHttpTask>();
      typed_task->AggregateIn(ctp::ipc::FullPtr<clio::run::Task>(member_task.get()));
      break;
    }
    default: {
      agg_task->AggregateIn(ctp::ipc::FullPtr<clio::run::Task>(member_task.get()));
      break;
    }
  }
}

} // namespace dt_provenance::proxy
